### ISSUE TITLE
issue templateと PR template作りなさい

### ISSUE THREAD

**Issue by mercy34mercy** [watnows/hackathon-2023-TeamA#68]
## feature
PRはチームの人に出してもらう時に、書いて欲しいことをtemplateにしておけばいいと思う。例えば、実装した部分、関連issue、特にみて欲しい部分、テスト方法とかかな。
Issueはなんか、毎回テンプレコピペしてそうだからとりあえず作ればくらいです。。。

## ref
 -  https://zenn.dev/ianchen0419/articles/0799b2f2831909

**Comment by YukaChoco** [comment]
なにこれ初めて知りました、即設定します
